---
language: java
sudo: false
git:
  submodules: false
  #https://github.com/travis-ci/travis-ci/issues/3412
  #Hack to get the revision number correct
  depth: 9999999 
branches:
    only:
        - master
        - 2_21
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
install: true
script: 
    - mvn -Ddocbkx.fopLogLevel=ERROR -q package 
after_success: 
    - bash ./.utility/deploy.sh
jdk:
    - openjdk7
notifications:
  email:
  - jason.p.pickering@gmail.com
env:
    global:
    - GH_REF: github.com/dhis2/dhis2-docs.git
    - secure: j8o/CjjpUHW5maKuroMnxWCXHqEnIB/l6DpUzARBBXs3klQahmCidxqAMkqTG5sdgMuXT1bv8LXI2pbCy5ZUxD32S13bypL9M4IKvJsCq7xqrUNQJ/Kys/Pb8DXvpq8ZY6ER/Df32NsUDoiBohseEP6rLfe6JFlW1HvtNmtP/o8=
